[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Jovasa <jovasa46@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"

[[bin]]
name = "day1"
path = "src/day1.rs"
